name: favlog_app
description: "A review app to log your favorite things."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  image_picker: ^1.2.1
  flutter_riverpod: ^2.5.1
  uuid: ^4.4.0
  flutter_dotenv: ^5.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  image: 4.2.0
  intl: ^0.19.0  # 日付フォーマット用に追加
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.3.2
  go_router: ^17.0.0
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.0
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/categories.json
    - .env
    - assets/fonts/
    - assets/images/

  fonts:
    - family: KosugiMaru
      fonts:
        - asset: assets/fonts/KosugiMaru-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
